language: java

# Fixes Travis memory issue
env:
  - JAVA_TOOL_OPTIONS="-Xmx2048m -Xms512m"

jdk:
  - oraclejdk8

# fixes SWT display problem
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - mvn clean verify
